version: "3"
services:
  domain:
    build:
      context: .
      dockerfile: Dockerfile
    # image: containous/whoami
    labels:
       # curl -H Host:tang.local http://127.0.0.1
       - "traefik.http.routers.cra.rule=Host(`tang.local`)"
networks:
  default:
    external:
      name: cra-ci-cd_default