version: "3"
services:
  cra:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.cra.rule=Host(`cra.tangzhenming.com`)"

networks:
  default:
    external:
      name: traefik_default 