name: Production

on:
  push:
    branches: ["main"]

jobs:
  your_job_id:
    # Job name is Deploy
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy cra
        run: docker compose up --build -d
