name: Production

on:
  push:
    branches: ["main"]

jobs:
  Deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: docker compose up --build -d
