name: Production

on:
  push:
    branches: ["main"]

jobs:
  deploy cra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run docker compose
        run: docker compose up --build -d
