name: Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: Deploy
      url: http://1.116.142.210:8888/
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: docker-compose up --build -d
        env:
          COMMIT_REF_NAME: ${{ github.ref_name }}
