name: production

on:
  push:
    branches: ["production"]

jobs:
  deploy_cra: # job's ID
    runs-on: self-hosted
    environment: # 在 github 仓库记录每个环境的标志已经对应环境的 url
      name: cra
      url: http://1.116.142.210:8888/
    steps:
      - uses: actions/checkout@v3
      - name: Run docker compose
        run: docker compose up --build -d
